### ISSUE TITLE
 AttributeError: 'NoneType' object has no attribute 'python_exit_status'

### ISSUE THREAD

**Issue by yuanzhang25** [szc19990412/TransMIL#26]
Hi，I met this error”AttributeError: 'NoneType' object has no attribute 'python_exit_status' ”when num_worker=8.Could you help me to solve this problem? BTW,when num_worker was set to 0,it alwasy train for 17 epoches and then stop no matter what number of epoch I set.

Here are the details for this error:

Traceback (most recent call last):
  File "train.py", line 92, in <module>
    main(cfg)
  File "train.py", line 70, in main
    trainer.fit(model = model, datamodule = dm)
  File "/home/amax/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 514, in fit
    self.dispatch()
  File "/home/amax/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 554, in dispatch
    self.accelerator.start_training(self)
  File "/home/amax/.local/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/amax/.local/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 111, in start_training
    self._results = trainer.run_train()
  File "/home/amax/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 645, in run_train
    self.train_loop.run_training_epoch()
  File "/home/amax/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 493, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/home/amax/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 632, in run_training_batch
    split_batch, batch_idx, opt_idx, optimizer, self.trainer.hiddens
  File "/home/amax/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 743, in training_step_and_backward
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/home/amax/.local/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 293, in training_step
    training_step_output = self.trainer.accelerator.training_step(args)
  File "/home/amax/.local/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 157, in training_step
    return self.training_type_plugin.training_step(*args)
  File "/home/amax/.local/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 122, in training_step
    return self.lightning_module.training_step(*args, **kwargs)
  File "/data3/TransMIL-main/models/model_interface.py", line 81, in training_step
    results_dict = self.model(data=data, label=label)
  File "/opt/anaconda3/envs/zy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data3/TransMIL-main/models/TransMIL.py", line 78, in forward
    h = self.layer1(h) #[B, N, 512]
  File "/opt/anaconda3/envs/zy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data3/TransMIL-main/models/TransMIL.py", line 24, in forward
    x = x + self.attn(self.norm(x))
  File "/opt/anaconda3/envs/zy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/amax/.local/lib/python3.7/site-packages/nystrom_attention/nystrom_attention.py", line 91, in forward
    q *= self.scale
RuntimeError: Output 0 of ReshapeAliasBackward0 is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fcbce250b00>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/zy/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1510, in __del__
  File "/opt/anaconda3/envs/zy/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1435, in _shutdown_workers
AttributeError: 'NoneType' object has no attribute 'python_exit_status'

**Comment by lcxlcx** [comment]
I have encountered the same problem, have you solved it?
